sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
- '6'
before_install:
- npm install -g -q bower
- npm install -g -q grunt-cli
install:
- npm install -q
before_script:
- ./node_modules/protractor/bin/webdriver-manager update
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
script:
- grunt eslint
- ./scripts/testserver.sh
- ./scripts/etcd.sh
- ./scripts/rune2etest.sh
sudo: false
